version: "3"

services:
  mysqldb:
        image: mariadb:10.2
        container_name: restaurant-db
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: restaurant
          MYSQL_PASSWORD: admin
          MYSQL_USER: admin
        ports:
          - "3306:3306"

  rest:
    build: .
    image: restaurant
    container_name: restaurant-app
    environment:
      - APP_MYSQL_DB=restaurant
      - APP_MYSQL_PORT=3306
      - APP_MYSQL_USERNAME=admin
      - APP_MYSQL_PASSWORD=admin
      - APP_MYSQL_DNS_SERVER=mysqldb
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysqldb
    links:
      - mysqldb
